# Generated by Django 5.0 on 2024-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_type', models.CharField(max_length=70)),
                ('model', models.CharField(max_length=70)),
                ('inst_date', models.DateField()),
                ('status', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': ('Equipment',),
                'verbose_name_plural': 'Equipments',
            },
        ),
    ]
